pipeline{
    agent any
    stages{
        stage{
            steps{
                sh "mvn clean install"
            }
        }
        stage{
            steps{
                sh "mvn test"
            }
        }
    }
}